# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plrlctl < Formula
  desc "CLI to manage and operate a fleet of clusters"
  homepage "https://docs.plural.sh"
  version "0.9.22"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.22/pluralctl_0.9.22_Darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "30ae4bfcb148fd80deafea145f417d4837b3829ce45e83692eec4788c6d2aaab"

      def install
        bin.install "pluralctl"
      end
    end
    on_arm do
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.22/pluralctl_0.9.22_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e4f6988a2af5833c138fbef1f592d6894c6beaff551ae43ec5c4a9abaa24a2ab"

      def install
        bin.install "pluralctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.22/pluralctl_0.9.22_Linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e7e5d8451d5829ce665392530374d8e065fa4dbd214dfd0a43c158af70349e2f"

        def install
          bin.install "pluralctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.22/pluralctl_0.9.22_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "247a93136eadc43fa8e7851dc14f43d518529200454413c0493b0e479c8d7e9c"

        def install
          bin.install "pluralctl"
        end
      end
    end
  end

  head "https://github.com/pluralsh/plural-cli.git"

  test do
    system "#{bin}/plrlctl", "--help"
  end
end
