# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plrlctl < Formula
  desc "CLI to manage and operate a fleet of clusters"
  homepage "https://docs.plural.sh"
  version "0.9.23"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.23/pluralctl_0.9.23_Darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "65ade86d6b0eb1cfa279a20e3af28727072ae81bfe19ff4a2ec998f6265eea63"

      def install
        bin.install "pluralctl"
      end
    end
    on_arm do
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.23/pluralctl_0.9.23_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2fb7fe6643e6c98fd063055d6369a675c2c9f49741e06d389a1475bdcbe2c565"

      def install
        bin.install "pluralctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.23/pluralctl_0.9.23_Linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "86d91acb4d239b3b5e53df63432d2c56b1da48f518eec6fcb6b04cc7c8ba7d53"

        def install
          bin.install "pluralctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pluralsh/plural-cli/releases/download/v0.9.23/pluralctl_0.9.23_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "a840d53969040d7baa3c763a1a260479207e7e4ae27b6970f519206de4ba4a70"

        def install
          bin.install "pluralctl"
        end
      end
    end
  end

  head "https://github.com/pluralsh/plural-cli.git"

  test do
    system "#{bin}/plrlctl", "--help"
  end
end
