# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plural < Formula
  desc "CLI for interacting with the plural platform"
  homepage "https://docs.plural.sh"
  version "0.12.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.12.15/plural-cli_0.12.15_Darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f3959c9be135d51c554ae5f0860c2ed0f231faf9a674851112182987b3da05fa"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.12.15/plural-cli_0.12.15_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d15829fd3c4ed143f59229e2437fdca203ba0bdcb422aa489afc8d7c8a37609b"

      def install
        bin.install "plural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.12.15/plural-cli_0.12.15_Linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "be148be73c1b530b76b6411223e44462d4b2357f63b9f1c59da76ed3b8666071"
      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.12.15/plural-cli_0.12.15_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f4c96601f4dc1d3b6469c959f0463b460eab7380ad1bed7ed6c020c716fe77af"
      def install
        bin.install "plural"
      end
    end
  end

  head "https://github.com/pluralsh/plural-cli.git"

  test do
    system "#{bin}/plural", "--help"
  end
end
