# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plural < Formula
  desc "CLI for interacting with the plural platform"
  homepage "https://docs.plural.sh"
  version "0.2.54"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/pluralsh/plural-cli/releases/v0.2.54/plural-cli_0.2.54_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e2a5fd9c50645ab4cbc304223974f693c18274c99d732a5aca1170b1d951c2bf"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/pluralsh/plural-cli/releases/v0.2.54/plural-cli_0.2.54_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "202e23452d7f584434b689c6fcdbaab401bdecf594242d3610c5a48070e37012"

      def install
        bin.install "plural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/pluralsh/plural-cli/releases/v0.2.54/plural-cli_0.2.54_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1c98f8010be5c17b4f99b7f9d9ce269a8d2838cfebb4ffdd403d8e378a4d79e7"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/pluralsh/plural-cli/releases/v0.2.54/plural-cli_0.2.54_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a1664aa3dc9b765425bb08556d03fd5e6528eb778c21df8ea15ffce7cc733562"

      def install
        bin.install "plural"
      end
    end
  end

  head "https://github.com/pluralsh/plural-cli.git"

  depends_on "go" => :build
  depends_on "helm" => :recommended
  depends_on "kubectl" => :recommended
  depends_on "terraform" => :recommended

  def post_install
    system "helm", "plugin", "install", "https://github.com/pluralsh/helm-push"
  end

  test do
    system "#{bin}/plural", "--help"
  end
end
