# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plural < Formula
  desc "CLI for interacting with the plural platform"
  homepage "https://docs.plural.sh"
  version "0.5.32"
  license "MIT"

  depends_on "helm" => :recommended
  depends_on "kubectl" => :recommended
  depends_on "terraform" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.5.32/plural-cli_0.5.32_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "310d7eea5aba6e39a78b48c3dd815f81289892f709f34272debc33d2149b71a9"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.5.32/plural-cli_0.5.32_Darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e38f9d3a37ab34353518e36da049c95811e37e53bb79b0822c9d4759140c1b3e"

      def install
        bin.install "plural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.5.32/plural-cli_0.5.32_Linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b9ef04cfe61e895187e3ed7969950a5e5055c1cc5038bae7abd9389b6ff0b46c"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pluralsh/plural-cli/releases/download/v0.5.32/plural-cli_0.5.32_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "070fa7d6d3025bcd628eff4de26e2845a9b5ee4512927dc8dcf75ef778f8de96"

      def install
        bin.install "plural"
      end
    end
  end

  head "https://github.com/pluralsh/plural-cli.git"

  test do
    system "#{bin}/plural", "--help"
  end
end
